<?php
/**
 * QuizArena — Phase A upgrade: gate + module loading.
 *
 * Access rules:
 *   Web: logged-in user with legacy role 'superadmin' AND the runner key
 *        (qa_settings.upg_runner_key, generated by a superadmin on this page).
 *   CLI: filesystem access IS the credential (staging drills via SSH), but the
 *        backup confirmation phrase is still required for every run action.
 *
 * This module NEVER executes anything by itself — index.php drives actions.
 */

require __DIR__ . '/../app/bootstrap.php';

if (!defined('QA_UPGRADE')) {
    define('QA_UPGRADE', true);
}

require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/handlers.php';
require_once __DIR__ . '/runner.php';

$UPG = [
    'cli'     => PHP_SAPI === 'cli',
    'authed'  => false,
    'reason'  => '',
    'user'    => null,
    'has_key' => false,
];

if ($UPG['cli']) {
    if (!QA_INSTALLED) {
        fwrite(STDERR, "ERROR: app/config.php not found — cannot run the upgrade without a configured database.\n");
        exit(1);
    }
    $UPG['authed'] = true;
} else {
    if (!QA_INSTALLED) {
        $UPG['reason'] = 'QuizArena is not installed yet. Run install.php first.';
    } else {
        $u = current_user();
        if (!$u) {
            $UPG['reason'] = 'Sign in with the Super Admin account to use the upgrade runner.';
        } elseif ($u['role'] !== 'superadmin') {
            http403('The upgrade runner is restricted to the Super Admin.');
        } elseif ((string) ($u['status'] ?? '') !== 'active') {
            $UPG['reason'] = 'This account is not active.';
        } else {
            $UPG['user'] = $u;
            $key = dbval("SELECT setting_value FROM qa_settings WHERE setting_key = 'upg_runner_key'");
            $UPG['has_key'] = $key !== null && $key !== '';
            if (!$UPG['has_key']) {
                $UPG['reason'] = 'Runner key not generated yet — generate it below (Super Admin only).';
            } elseif (!hash_equals((string) $key, (string) ($_REQUEST['key'] ?? ''))) {
                $UPG['reason'] = 'Invalid or missing runner key. Append ?key=… to the URL.';
            } else {
                $UPG['authed'] = true;
            }
        }
    }
}
