<?php
/**
 * QuizArena — Phase A upgrade: the 20 NEW tables (locked v3.3 schema).
 *
 * Conventions (matching the existing 26-table legacy schema):
 *  - ENGINE=InnoDB, utf8mb4 / utf8mb4_unicode_ci.
 *  - NO FOREIGN KEY constraints anywhere (legacy convention); relations are
 *    logical, enforced by application rules + the verification suite.
 *  - All money is stored as integer paise (INR × 100) — zero floats in the
 *    new accounting domain. Legacy DECIMAL(10,2) subscription tables are
 *    untouched.
 *  - 'cols' mirrors each CREATE TABLE as name => MySQL COLUMN_TYPE. It is
 *    used by guard_create_table() for exact live-shape verification and is
 *    cross-checked against the SQL by the Phase A validation harness.
 *
 * Unique-index registry (locked): uq_region, uq_referred, uq_code_referred,
 * uq_payout_key, uq_ledger_key, uq_cat_name, uq_sku, uq_shop_seller,
 * uq_invoice, uq_stock_key (+ uq_referral_code added by migration step 24).
 * All uq_* are UNIQUE; all idx_* are non-UNIQUE.
 */

if (!defined('QA_RUNNING')) { exit('Direct access denied'); }

return [

'qa_regions' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_regions (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type ENUM('state','district','city') NOT NULL,
    name VARCHAR(120) NOT NULL,
    parent_id INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uq_region (type, name, parent_id),
    KEY idx_parent (parent_id),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'INT UNSIGNED',
        'type' => "ENUM('state','district','city')",
        'name' => 'VARCHAR(120)',
        'parent_id' => 'INT UNSIGNED',
        'status' => "ENUM('active','inactive')",
        'created_by' => 'INT UNSIGNED',
        'created_at' => 'DATETIME',
    ],
],

'qa_network' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_network (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    role ENUM('salesperson','city_head','district_head','state_head') NOT NULL,
    region_id INT UNSIGNED NOT NULL,
    status ENUM('active','retired') NOT NULL DEFAULT 'active',
    appointed_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    retired_at DATETIME NULL,
    retire_reason VARCHAR(255) NULL,
    KEY idx_level_region (role, region_id, status),
    KEY idx_user (user_id),
    KEY idx_region (region_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'INT UNSIGNED',
        'user_id' => 'INT UNSIGNED',
        'role' => "ENUM('salesperson','city_head','district_head','state_head')",
        'region_id' => 'INT UNSIGNED',
        'status' => "ENUM('active','retired')",
        'appointed_by' => 'INT UNSIGNED',
        'created_at' => 'DATETIME',
        'retired_at' => 'DATETIME',
        'retire_reason' => 'VARCHAR(255)',
    ],
],

'qa_referrals' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_referrals (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    referrer_user_id INT UNSIGNED NOT NULL,
    referred_user_id INT UNSIGNED NOT NULL,
    code_used VARCHAR(20) NOT NULL,
    referrer_region_id INT UNSIGNED NULL,
    status ENUM('active','reversed') NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    reversed_at DATETIME NULL,
    UNIQUE KEY uq_referred (referred_user_id),
    UNIQUE KEY uq_code_referred (code_used, referred_user_id),
    KEY idx_referrer (referrer_user_id),
    KEY idx_referrer_region (referrer_region_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'INT UNSIGNED',
        'referrer_user_id' => 'INT UNSIGNED',
        'referred_user_id' => 'INT UNSIGNED',
        'code_used' => 'VARCHAR(20)',
        'referrer_region_id' => 'INT UNSIGNED',
        'status' => "ENUM('active','reversed')",
        'created_at' => 'DATETIME',
        'reversed_at' => 'DATETIME',
    ],
],

'qa_referral_events' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_referral_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    referral_id INT UNSIGNED NOT NULL,
    event ENUM('registered','rewarded','reversed') NOT NULL,
    wallet_txn_id INT UNSIGNED NULL,
    ledger_id BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    KEY idx_referral (referral_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'referral_id' => 'INT UNSIGNED',
        'event' => "ENUM('registered','rewarded','reversed')",
        'wallet_txn_id' => 'INT UNSIGNED',
        'ledger_id' => 'BIGINT UNSIGNED',
        'created_at' => 'DATETIME',
    ],
],

'qa_withdrawals' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_withdrawals (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    coins INT NOT NULL,
    coin_value INT NOT NULL,
    inr_amount BIGINT NOT NULL,
    fee_amount BIGINT NOT NULL DEFAULT 0,
    net_amount BIGINT NOT NULL DEFAULT 0,
    status ENUM('pending','approved','paid','rejected','reversed') NOT NULL DEFAULT 'pending',
    payout_method VARCHAR(50) NULL,
    payout_ref VARCHAR(100) NULL,
    decision_reason VARCHAR(255) NULL,
    requested_at DATETIME NOT NULL,
    decided_by INT UNSIGNED NULL,
    decided_at DATETIME NULL,
    paid_at DATETIME NULL,
    KEY idx_user (user_id),
    KEY idx_status (status),
    KEY idx_requested (requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'user_id' => 'INT UNSIGNED',
        'coins' => 'INT',
        'coin_value' => 'INT',
        'inr_amount' => 'BIGINT',
        'fee_amount' => 'BIGINT',
        'net_amount' => 'BIGINT',
        'status' => "ENUM('pending','approved','paid','rejected','reversed')",
        'payout_method' => 'VARCHAR(50)',
        'payout_ref' => 'VARCHAR(100)',
        'decision_reason' => 'VARCHAR(255)',
        'requested_at' => 'DATETIME',
        'decided_by' => 'INT UNSIGNED',
        'decided_at' => 'DATETIME',
        'paid_at' => 'DATETIME',
    ],
],

'qa_commission_rules' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_commission_rules (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    source_type ENUM('purchase','offline_sale') NOT NULL,
    beneficiary_role ENUM('seller','salesperson','city_head','district_head','state_head','referral') NOT NULL,
    rate_type ENUM('percent_bp','flat_paise') NOT NULL DEFAULT 'percent_bp',
    rate_value INT NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    KEY idx_source (source_type, status),
    KEY idx_priority (source_type, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'INT UNSIGNED',
        'name' => 'VARCHAR(120)',
        'source_type' => "ENUM('purchase','offline_sale')",
        'beneficiary_role' => "ENUM('seller','salesperson','city_head','district_head','state_head','referral')",
        'rate_type' => "ENUM('percent_bp','flat_paise')",
        'rate_value' => 'INT',
        'priority' => 'INT',
        'status' => "ENUM('active','inactive')",
        'created_at' => 'DATETIME',
        'updated_at' => 'DATETIME',
    ],
],

'qa_commissions' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_commissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payout_key VARCHAR(120) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    rule_id INT UNSIGNED NOT NULL,
    source_type ENUM('purchase','offline_sale') NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    line_no INT UNSIGNED NULL,
    beneficiary_user_id INT UNSIGNED NOT NULL,
    beneficiary_role ENUM('seller','salesperson','city_head','district_head','state_head','referral') NOT NULL,
    amount BIGINT NOT NULL DEFAULT 0,
    coin_amount INT NOT NULL DEFAULT 0,
    coin_value INT NOT NULL DEFAULT 0,
    reversal_of BIGINT UNSIGNED NULL,
    status ENUM('active','reversed') NOT NULL DEFAULT 'active',
    hierarchy_snapshot TEXT NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uq_payout_key (payout_key),
    KEY idx_source (source_type, source_id),
    KEY idx_beneficiary (beneficiary_user_id),
    KEY idx_reversal_of (reversal_of)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'payout_key' => 'VARCHAR(120)',
        'payload_hash' => 'CHAR(64)',
        'rule_id' => 'INT UNSIGNED',
        'source_type' => "ENUM('purchase','offline_sale')",
        'source_id' => 'BIGINT UNSIGNED',
        'line_no' => 'INT UNSIGNED',
        'beneficiary_user_id' => 'INT UNSIGNED',
        'beneficiary_role' => "ENUM('seller','salesperson','city_head','district_head','state_head','referral')",
        'amount' => 'BIGINT',
        'coin_amount' => 'INT',
        'coin_value' => 'INT',
        'reversal_of' => 'BIGINT UNSIGNED',
        'status' => "ENUM('active','reversed')",
        'hierarchy_snapshot' => 'TEXT',
        'created_at' => 'DATETIME',
    ],
],

'qa_company_ledger' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_company_ledger (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idempotency_key VARCHAR(120) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    source_type ENUM('order','offline_sale','quiz','refund','offline_refund','quiz_refund','referral','referral_reversal','signup','withdrawal','withdrawal_reversal','adjustment') NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    class ENUM('revenue','expense') NOT NULL,
    gross BIGINT NOT NULL DEFAULT 0,
    fees BIGINT NOT NULL DEFAULT 0,
    taxes BIGINT NOT NULL DEFAULT 0,
    customer_reward BIGINT NOT NULL DEFAULT 0,
    customer_user_id INT UNSIGNED NULL,
    commission_seller BIGINT NOT NULL DEFAULT 0,
    seller_user_id INT UNSIGNED NULL,
    commission_salesperson BIGINT NOT NULL DEFAULT 0,
    salesperson_user_id INT UNSIGNED NULL,
    commission_city BIGINT NOT NULL DEFAULT 0,
    city_user_id INT UNSIGNED NULL,
    commission_district BIGINT NOT NULL DEFAULT 0,
    district_user_id INT UNSIGNED NULL,
    commission_state BIGINT NOT NULL DEFAULT 0,
    state_user_id INT UNSIGNED NULL,
    commission_referral BIGINT NOT NULL DEFAULT 0,
    referral_user_id INT UNSIGNED NULL,
    withdrawal_amount BIGINT NOT NULL DEFAULT 0,
    adjustment_amount BIGINT NOT NULL DEFAULT 0,
    company_share BIGINT NOT NULL DEFAULT 0,
    coin_amount INT NOT NULL DEFAULT 0,
    coin_value INT NOT NULL DEFAULT 0,
    rounding_diff BIGINT NOT NULL DEFAULT 0,
    reversal_of BIGINT UNSIGNED NULL,
    status ENUM('active','partially_reversed','reversed') NOT NULL DEFAULT 'active',
    audit_ref VARCHAR(120) NULL,
    note VARCHAR(255) NULL,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uq_ledger_key (idempotency_key),
    KEY idx_source (source_type, source_id),
    KEY idx_class (class),
    KEY idx_status (status),
    KEY idx_reversal_of (reversal_of),
    KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'idempotency_key' => 'VARCHAR(120)',
        'payload_hash' => 'CHAR(64)',
        'source_type' => "ENUM('order','offline_sale','quiz','refund','offline_refund','quiz_refund','referral','referral_reversal','signup','withdrawal','withdrawal_reversal','adjustment')",
        'source_id' => 'BIGINT UNSIGNED',
        'class' => "ENUM('revenue','expense')",
        'gross' => 'BIGINT',
        'fees' => 'BIGINT',
        'taxes' => 'BIGINT',
        'customer_reward' => 'BIGINT',
        'customer_user_id' => 'INT UNSIGNED',
        'commission_seller' => 'BIGINT',
        'seller_user_id' => 'INT UNSIGNED',
        'commission_salesperson' => 'BIGINT',
        'salesperson_user_id' => 'INT UNSIGNED',
        'commission_city' => 'BIGINT',
        'city_user_id' => 'INT UNSIGNED',
        'commission_district' => 'BIGINT',
        'district_user_id' => 'INT UNSIGNED',
        'commission_state' => 'BIGINT',
        'state_user_id' => 'INT UNSIGNED',
        'commission_referral' => 'BIGINT',
        'referral_user_id' => 'INT UNSIGNED',
        'withdrawal_amount' => 'BIGINT',
        'adjustment_amount' => 'BIGINT',
        'company_share' => 'BIGINT',
        'coin_amount' => 'INT',
        'coin_value' => 'INT',
        'rounding_diff' => 'BIGINT',
        'reversal_of' => 'BIGINT UNSIGNED',
        'status' => "ENUM('active','partially_reversed','reversed')",
        'audit_ref' => 'VARCHAR(120)',
        'note' => 'VARCHAR(255)',
        'created_by' => 'INT UNSIGNED',
        'created_at' => 'DATETIME',
    ],
],

'qa_product_categories' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_product_categories (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uq_cat_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'INT UNSIGNED',
        'name' => 'VARCHAR(120)',
        'status' => "ENUM('active','inactive')",
        'created_by' => 'INT UNSIGNED',
        'created_at' => 'DATETIME',
    ],
],

'qa_products' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    category_id INT UNSIGNED NULL,
    sku VARCHAR(60) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    price_paise BIGINT NOT NULL DEFAULT 0,
    mrp_paise BIGINT NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    low_stock_threshold INT NOT NULL DEFAULT 5,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uq_sku (sku),
    KEY idx_category (category_id),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'category_id' => 'INT UNSIGNED',
        'sku' => 'VARCHAR(60)',
        'name' => 'VARCHAR(200)',
        'description' => 'TEXT',
        'price_paise' => 'BIGINT',
        'mrp_paise' => 'BIGINT',
        'stock' => 'INT',
        'low_stock_threshold' => 'INT',
        'status' => "ENUM('active','inactive')",
        'created_at' => 'DATETIME',
        'updated_at' => 'DATETIME',
    ],
],

'qa_shops' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_shops (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    seller_user_id INT UNSIGNED NOT NULL,
    shop_name VARCHAR(150) NOT NULL,
    region_id INT UNSIGNED NULL,
    address VARCHAR(255) NULL,
    status ENUM('active','inactive') NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uq_shop_seller (seller_user_id),
    KEY idx_region (region_id),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'seller_user_id' => 'INT UNSIGNED',
        'shop_name' => 'VARCHAR(150)',
        'region_id' => 'INT UNSIGNED',
        'address' => 'VARCHAR(255)',
        'status' => "ENUM('active','inactive')",
        'created_at' => 'DATETIME',
        'updated_at' => 'DATETIME',
    ],
],

'qa_orders' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(30) NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    items_total BIGINT NOT NULL DEFAULT 0,
    discount BIGINT NOT NULL DEFAULT 0,
    taxes BIGINT NOT NULL DEFAULT 0,
    grand_total BIGINT NOT NULL DEFAULT 0,
    coins_used INT NOT NULL DEFAULT 0,
    coins_value_used BIGINT NOT NULL DEFAULT 0,
    status ENUM('pending','paid','shipped','delivered','cancelled','refunded','partially_refunded') NOT NULL DEFAULT 'pending',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    UNIQUE KEY uq_order_no (order_no),
    KEY idx_user (user_id),
    KEY idx_status (status),
    KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'order_no' => 'VARCHAR(30)',
        'user_id' => 'INT UNSIGNED',
        'items_total' => 'BIGINT',
        'discount' => 'BIGINT',
        'taxes' => 'BIGINT',
        'grand_total' => 'BIGINT',
        'coins_used' => 'INT',
        'coins_value_used' => 'BIGINT',
        'status' => "ENUM('pending','paid','shipped','delivered','cancelled','refunded','partially_refunded')",
        'created_at' => 'DATETIME',
        'updated_at' => 'DATETIME',
    ],
],

'qa_order_items' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_order_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    qty INT NOT NULL,
    unit_price_paise BIGINT NOT NULL,
    line_total_paise BIGINT NOT NULL,
    refunded_qty INT NOT NULL DEFAULT 0,
    KEY idx_order (order_id),
    KEY idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'order_id' => 'BIGINT UNSIGNED',
        'product_id' => 'BIGINT UNSIGNED',
        'qty' => 'INT',
        'unit_price_paise' => 'BIGINT',
        'line_total_paise' => 'BIGINT',
        'refunded_qty' => 'INT',
    ],
],

'qa_offline_sales' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_offline_sales (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    seller_user_id INT UNSIGNED NOT NULL,
    shop_id BIGINT UNSIGNED NULL,
    invoice_number VARCHAR(40) NOT NULL,
    items_total BIGINT NOT NULL DEFAULT 0,
    discount BIGINT NOT NULL DEFAULT 0,
    taxes BIGINT NOT NULL DEFAULT 0,
    grand_total BIGINT NOT NULL DEFAULT 0,
    customer_name VARCHAR(150) NULL,
    customer_mobile VARCHAR(20) NULL,
    sale_date DATE NOT NULL,
    status ENUM('active','refunded','partially_refunded') NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    created_by INT UNSIGNED NULL,
    UNIQUE KEY uq_invoice (seller_user_id, invoice_number),
    KEY idx_seller (seller_user_id),
    KEY idx_date (sale_date),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'seller_user_id' => 'INT UNSIGNED',
        'shop_id' => 'BIGINT UNSIGNED',
        'invoice_number' => 'VARCHAR(40)',
        'items_total' => 'BIGINT',
        'discount' => 'BIGINT',
        'taxes' => 'BIGINT',
        'grand_total' => 'BIGINT',
        'customer_name' => 'VARCHAR(150)',
        'customer_mobile' => 'VARCHAR(20)',
        'sale_date' => 'DATE',
        'status' => "ENUM('active','refunded','partially_refunded')",
        'created_at' => 'DATETIME',
        'created_by' => 'INT UNSIGNED',
    ],
],

'qa_offline_sale_items' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_offline_sale_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    offline_sale_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    qty INT NOT NULL,
    unit_price_paise BIGINT NOT NULL,
    line_total_paise BIGINT NOT NULL,
    refunded_qty INT NOT NULL DEFAULT 0,
    KEY idx_sale (offline_sale_id),
    KEY idx_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'offline_sale_id' => 'BIGINT UNSIGNED',
        'product_id' => 'BIGINT UNSIGNED',
        'qty' => 'INT',
        'unit_price_paise' => 'BIGINT',
        'line_total_paise' => 'BIGINT',
        'refunded_qty' => 'INT',
    ],
],

'qa_stock_movements' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_stock_movements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    product_id BIGINT UNSIGNED NOT NULL,
    type ENUM('purchase_in','sale','offline_sale','refund_in','offline_refund_in','cancel_return','adjust_in','adjust_out','initial') NOT NULL,
    delta INT NOT NULL,
    balance_after INT NULL,
    ref_type VARCHAR(40) NOT NULL DEFAULT '',
    ref_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(120) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    note VARCHAR(255) NULL,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uq_stock_key (idempotency_key),
    KEY idx_product (product_id, created_at),
    KEY idx_ref (ref_type, ref_id),
    KEY idx_type (type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'product_id' => 'BIGINT UNSIGNED',
        'type' => "ENUM('purchase_in','sale','offline_sale','refund_in','offline_refund_in','cancel_return','adjust_in','adjust_out','initial')",
        'delta' => 'INT',
        'balance_after' => 'INT',
        'ref_type' => 'VARCHAR(40)',
        'ref_id' => 'BIGINT UNSIGNED',
        'idempotency_key' => 'VARCHAR(120)',
        'payload_hash' => 'CHAR(64)',
        'note' => 'VARCHAR(255)',
        'created_by' => 'INT UNSIGNED',
        'created_at' => 'DATETIME',
    ],
],

'qa_question_imports' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_question_imports (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    uploaded_by INT UNSIGNED NOT NULL,
    quiz_id INT UNSIGNED NULL,
    audience ENUM('school','general') NULL,
    status ENUM('pending','validated','committed','failed') NOT NULL DEFAULT 'pending',
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    invalid_rows INT NOT NULL DEFAULT 0,
    error_summary TEXT NULL,
    created_at DATETIME NOT NULL,
    committed_at DATETIME NULL,
    KEY idx_uploader (uploaded_by),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'INT UNSIGNED',
        'filename' => 'VARCHAR(255)',
        'uploaded_by' => 'INT UNSIGNED',
        'quiz_id' => 'INT UNSIGNED',
        'audience' => "ENUM('school','general')",
        'status' => "ENUM('pending','validated','committed','failed')",
        'total_rows' => 'INT',
        'valid_rows' => 'INT',
        'invalid_rows' => 'INT',
        'error_summary' => 'TEXT',
        'created_at' => 'DATETIME',
        'committed_at' => 'DATETIME',
    ],
],

'qa_question_import_rows' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_question_import_rows (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    import_id INT UNSIGNED NOT NULL,
    row_no INT NOT NULL,
    raw_data TEXT NOT NULL,
    question_text TEXT NULL,
    options_json TEXT NULL,
    correct_option INT NULL,
    explanation TEXT NULL,
    status ENUM('pending','valid','invalid','imported') NOT NULL DEFAULT 'pending',
    error_msg VARCHAR(500) NULL,
    question_id INT UNSIGNED NULL,
    KEY idx_import (import_id, row_no),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'import_id' => 'INT UNSIGNED',
        'row_no' => 'INT',
        'raw_data' => 'TEXT',
        'question_text' => 'TEXT',
        'options_json' => 'TEXT',
        'correct_option' => 'INT',
        'explanation' => 'TEXT',
        'status' => "ENUM('pending','valid','invalid','imported')",
        'error_msg' => 'VARCHAR(500)',
        'question_id' => 'INT UNSIGNED',
    ],
],

'qa_audit_log' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_audit_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    actor_user_id INT UNSIGNED NOT NULL,
    action VARCHAR(120) NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_id BIGINT UNSIGNED NULL,
    old_value LONGTEXT NULL,
    new_value LONGTEXT NULL,
    reason VARCHAR(255) NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    source_ref VARCHAR(120) NULL,
    created_at DATETIME NOT NULL,
    KEY idx_actor (actor_user_id, created_at),
    KEY idx_entity (entity_type, entity_id),
    KEY idx_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'actor_user_id' => 'INT UNSIGNED',
        'action' => 'VARCHAR(120)',
        'entity_type' => 'VARCHAR(60)',
        'entity_id' => 'BIGINT UNSIGNED',
        'old_value' => 'LONGTEXT',
        'new_value' => 'LONGTEXT',
        'reason' => 'VARCHAR(255)',
        'ip_address' => 'VARCHAR(45)',
        'user_agent' => 'VARCHAR(255)',
        'source_ref' => 'VARCHAR(120)',
        'created_at' => 'DATETIME',
    ],
],

'qa_reg_attempts' => [
    'sql'  => "CREATE TABLE IF NOT EXISTS qa_reg_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    identifier VARCHAR(150) NOT NULL,
    ip_address VARCHAR(45) NULL,
    code_attempted VARCHAR(20) NULL,
    attempts INT NOT NULL DEFAULT 1,
    first_attempt_at DATETIME NOT NULL,
    last_attempt_at DATETIME NOT NULL,
    blocked_until DATETIME NULL,
    KEY idx_identifier (identifier, last_attempt_at),
    KEY idx_ip (ip_address, last_attempt_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'cols' => [
        'id' => 'BIGINT UNSIGNED',
        'identifier' => 'VARCHAR(150)',
        'ip_address' => 'VARCHAR(45)',
        'code_attempted' => 'VARCHAR(20)',
        'attempts' => 'INT',
        'first_attempt_at' => 'DATETIME',
        'last_attempt_at' => 'DATETIME',
        'blocked_until' => 'DATETIME',
    ],
],
];
